/**
 * Finds the item ID of each "Used For" target that needs a value (hats, pet
 * evolutions and so on; see src/utils/targets.js), for admin mode's Targets
 * page, and writes them to src/data/target-ids.json.
 *
 * Names are matched with Hercules pre-renewal first, then rAthena renewal,
 * ignoring case, spaces and punctuation. A pet evolution's ID is the evolved
 * pet's egg (that's what players trade). Names that don't match go in
 * AEGIS_NAMES below, by the emulators' exact item code, or in ITEM_IDS
 * when the emulators don't name the item at all.
 *
 * Usage:
 *   npm run sync:targets             (update target-ids.json)
 *   npm run sync:targets -- --check  (only report, change nothing)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { loadPreRenewalItemDb } from './hercules.mjs';
import { loadRenewalItemDb } from './rathena.mjs';
import { valueTargets } from '../src/utils/targets.js';

const LOOT_FILE = 'src/data/loot.json';
const IDS_FILE = 'src/data/target-ids.json';
const checkOnly = process.argv.includes('--check');

/** Targets whose uaRO name doesn't match the emulators: target -> AegisName. */
const AEGIS_NAMES = {
  'Glaris Doll': 'Claris_Doll_Hat',
  'Defolty Doll': 'Deprotai_Doll_Hat',
  'Rideword Hat (RWH)': 'Rideword_Hat',
  'Orc Hero Helm': 'Orc_Hero_Helm',
  'Pecopeco Wing Ears': 'Pecopeco_Wing_Ears',
  // Eggs (rAthena's pet_db.yml)
  'Moonlight Flower Pet Evolution': 'Moonlight_Egg',
  "Cat o' Nine Tails Pet Evolution": 'Cat_O_Nine_Tail_Egg',
  'Grand Peco Pet Evolution': 'Grand_Peco_Egg',
  'Abandoned Teddy Bear Pet Evolution': 'Xm_Teddybear_Egg',
  'Skelion Pet Evolution': 'Roost_Of_Skelion',
  'Chaotic Baphomet Jr Pet Evolution': 'Chaos_Bapho_Jr_Egg',
};

/** Targets whose item the emulators don't name: target -> item ID (from the maintainer). */
const ITEM_IDS = {
  'Mistress Pet Evolution': 9193, // Mistress Egg; rAthena only has it as aegis_9193
  'Earth Deleter Pet Evolution': 9098,
  'Gigantic Majestic Goat (DEF)': 5518,
  'Antique Smoking Pipe': 5377,
};

const items = JSON.parse(readFileSync(LOOT_FILE, 'utf8'));
const key = (name) => name.toLowerCase().replace(/\s*\[\d\]$/, '').replace(/[^a-z0-9]/g, '');

// Pre-renewal last, so its IDs win when both have the name.
const idByName = new Map();
const idByAegis = new Map();
for (const db of [await loadRenewalItemDb(), await loadPreRenewalItemDb()]) {
  for (const item of db.values()) {
    if (item.name) idByName.set(key(item.name), item.id);
    if (item.aegisName) idByAegis.set(item.aegisName, item.id);
  }
}

/** "Yao Jun Pet Evolution (Hyegun)" -> the names to try for its egg. */
function eggNames(target) {
  const [, pet, alsoKnownAs] = target.match(/^(.*?) Pet Evolution(?: \((.*)\))?$/);
  return [pet, alsoKnownAs].filter(Boolean).map((name) => `${name} Egg`);
}

const ids = {};
const missing = [];
for (const target of valueTargets(items).values()) {
  const names = / Pet Evolution/.test(target.name) ? eggNames(target.name) : [target.name];
  const id = ITEM_IDS[target.name] ?? (AEGIS_NAMES[target.name]
    ? idByAegis.get(AEGIS_NAMES[target.name])
    : names.map((name) => idByName.get(key(name))).find(Boolean));
  if (id) ids[target.name] = id;
  else missing.push(target.name);
}

const sorted = Object.fromEntries(Object.entries(ids).sort(([a], [b]) => a.localeCompare(b)));
console.log(`${Object.keys(sorted).length} targets have an item ID.`);
if (missing.length) console.log(`No match for ${missing.length} (add them to AEGIS_NAMES): ${missing.join(', ')}`);
if (!checkOnly) {
  const about = 'Generated by `npm run sync:targets`. Item IDs of "Used For" targets that aren\'t loot, for admin mode\'s Targets page. Pet evolutions use the evolved pet\'s egg.';
  writeFileSync(IDS_FILE, JSON.stringify({ about, ids: sorted }, null, 2) + '\n');
}
